In [1]:
import numpy as np
file_path = "C:\\fpoly\\Numpy\\Assignment\\"
file_data = "Covid-19-Final.csv"
datafile = file_path + file_data
print(datafile)

C:\fpoly\Numpy\Assignment\Covid-19-Final.csv


In [2]:
myDelimiter = ','
maxline = 10
np.set_printoptions(suppress=True,precision=2,linewidth=150)

In [3]:
raw_data_header = np.loadtxt(datafile,
                     delimiter = myDelimiter,
                     dtype = np.str_,
                     max_rows = 1)
print(raw_data_header)

['SNo' 'ObservationDate' 'Province/State' 'Country/Region' 'Last Update' 'Confirmed' 'Deaths' 'Recovered' 'observation_MM' 'observation_DD'
 'observation_YYYY' 'State_ID' 'Country_ID']


In [4]:
indeces_raw = [0,8,9,10,5,6,7]
raw_data = np.genfromtxt(datafile,
                        usecols = indeces_raw,
                        delimiter = myDelimiter,
                        skip_header = True)
print(raw_data)
print(raw_data.shape)


[[     1.      1.     22. ...      1.      0.      0.]
 [     2.      1.     22. ...     14.      0.      0.]
 [     3.      1.     22. ...      6.      0.      0.]
 ...
 [306427.      5.     29. ...   1364.      1.   1324.]
 [306428.      5.     29. ...  87550.   1738.  83790.]
 [306429.      5.     29. ... 391559.   4252.      0.]]
(306429, 7)


In [5]:
SNo_cIdx = 0
MM_cIdx = 1
DD_cIdx = 2
YYYY_cIdx = 3
cofirmed_cIdx = 4
deaths_cIdx = 5
recoverds_cIdx = 6

In [6]:
#Sắp xếp 1 cột YYYY
indeces_sortYYYY = np.argsort(raw_data[:,YYYY_cIdx])
sort_data_YYYY = raw_data[indeces_sortYYYY]
print(sort_data_YYYY)

[[ 38304.      6.      8. ...   3611.     10.   3543.]
 [     2.      1.     22. ...     14.      0.      0.]
 [     3.      1.     22. ...      6.      0.      0.]
 ...
 [306428.      5.     29. ...  87550.   1738.  83790.]
 [306429.      5.     29. ... 391559.   4252.      0.]
 [268126.      4.      9. ... 389353.   2157.      0.]]


In [7]:
#Sắp xếp nhìu cột số ca nhiễm
indeces_sortcofimed = np.argsort(raw_data[:,cofirmed_cIdx])
sort_data_cofimed  = raw_data[indeces_sortcofimed]
print(sort_data_cofimed)


[[ 147525.      11.       2. ... -302844.       0.       0.]
 [ 280717.       4.      26. ...       0.       1.       0.]
 [  52209.       6.      27. ...       0.       0.  164024.]
 ...
 [ 296539.       5.      17. ... 5829009.  107041.  321874.]
 [ 297304.       5.      18. ... 5845010.  107256.  323205.]
 [ 298069.       5.      19. ... 5863138.  107390.  324444.]]


### 
- Sắp xếp mảng theo thời gian khảo sát để hiểu rõ hơn về xu hướng phát triển của dịch bệnh. 
- Sắp xếp dữ liệu theo số ca nhiễm từ thấp đến cao để xác định các quốc gia ổn định. 
- Sắp xếp mảng theo thứ tự tử vong tăng dần để đánh giá tình hình nguy cấp. 

In [8]:
#Sắp xếp nhiều cột Date(YYYY,MM,DD,cofirmed)
indeces_date_cofirmed = np.lexsort((-raw_data[:,DD_cIdx],
                          raw_data[:,MM_cIdx],
                          -raw_data[:,YYYY_cIdx],
                          raw_data[:,cofirmed_cIdx]))
sort_data = raw_data[indeces_date_cofirmed]
print(sort_data)
header_y1_03 = raw_data_header[indeces_raw]
print(header_y1_03)
y1_03_header_string = ",".join(header_y1_03)
print(y1_03_header_string)
file_name = 'Trend_Cofimed_Date_Data.csv'
datafile = file_path + file_name
np.savetxt(datafile,sort_data,delimiter = myDelimiter,header =y1_03_header_string, fmt = "%s")

[[ 147525.      11.       2. ... -302844.       0.       0.]
 [ 215475.       1.      31. ...       0.       0.       0.]
 [ 215692.       1.      31. ...       0.       1.       0.]
 ...
 [ 296539.       5.      17. ... 5829009.  107041.  321874.]
 [ 297304.       5.      18. ... 5845010.  107256.  323205.]
 [ 298069.       5.      19. ... 5863138.  107390.  324444.]]
['SNo' 'observation_MM' 'observation_DD' 'observation_YYYY' 'Confirmed' 'Deaths' 'Recovered']
SNo,observation_MM,observation_DD,observation_YYYY,Confirmed,Deaths,Recovered


### 
- Xác định ngày có số ca nhiễm và tử vong cao nhất và thấp nhất. 


In [9]:
#print(raw_data)
max_index_Cofirmed = np.argmax(raw_data[:,cofirmed_cIdx])
max_column_Cofirmed = raw_data[max_index_Cofirmed]
print("Ca nhiễm cao nhất:\n",max_column_Cofirmed)

max_index_Deaths = np.argmax(raw_data[:,deaths_cIdx])
max_column_Deaths = raw_data[max_index_Deaths]
print("Ca tử vong cao nhất:\n",max_column_Deaths)

min_index_Cofirmed = np.argmin(raw_data[:,cofirmed_cIdx])
min_column_Cofirmed = raw_data[min_index_Cofirmed]
print("Ca nhiễm thấp nhất:\n",min_column_Cofirmed)

min_index_Deaths = np.argmin(raw_data[:,deaths_cIdx])
min_column_Deaths = raw_data[min_index_Deaths]
print("Ca tử vong thấp nhất:\n",min_column_Deaths)


Ca nhiễm cao nhất:
 [ 298069.       5.      19.    2021. 5863138.  107390.  324444.]
Ca tử vong cao nhất:
 [ 305973.       5.      29.    2021. 3910803.  112385.       0.]
Ca nhiễm thấp nhất:
 [ 147525.      11.       2.    2020. -302844.       0.       0.]
Ca tử vong thấp nhất:
 [118364.      9.     24.   2020.      0.   -178. -12684.]


In [10]:
indeces_sortmax_Cofirmed_Deaths = np.lexsort((-raw_data[:,deaths_cIdx],-raw_data[:,cofirmed_cIdx]))
data_sortmax_Cofirmed_Deaths = raw_data[indeces_sortmax_Cofirmed_Deaths]
print(data_sortmax_Cofirmed_Deaths[0])

indeces_sortmin_Cofirmed_Deaths = np.lexsort((raw_data[:,deaths_cIdx],raw_data[:,cofirmed_cIdx]))
data_sortmin_Cofirmed_Deaths = raw_data[indeces_sortmin_Cofirmed_Deaths]
print(data_sortmin_Cofirmed_Deaths[0])

[ 298069.       5.      19.    2021. 5863138.  107390.  324444.]
[ 147525.      11.       2.    2020. -302844.       0.       0.]


###
- Tìm ngày có số ca nhiễm tăng mạnh nhất so với ngày trước đó. 

In [11]:
indeces_date = np.lexsort((raw_data[:,DD_cIdx],
                          raw_data[:,MM_cIdx],
                          raw_data[:,YYYY_cIdx],
                          ))
sort_data_byDate = raw_data[indeces_date]
print(sort_data_byDate)

[[     1.      1.     22. ...      1.      0.      0.]
 [     2.      1.     22. ...     14.      0.      0.]
 [     3.      1.     22. ...      6.      0.      0.]
 ...
 [306427.      5.     29. ...   1364.      1.   1324.]
 [306428.      5.     29. ...  87550.   1738.  83790.]
 [306429.      5.     29. ... 391559.   4252.      0.]]


In [12]:
newValue_byDate = np.diff(sort_data_byDate[:,cofirmed_cIdx])
print(newValue_byDate.shape)
print(newValue_byDate)

max_value = np.max(newValue_byDate)
print("Max value:", max_value)
arg_max = np.argmax(max_value)
print(newValue_byDate[arg_max])

(306428,)
[    13.     -8.     -5. ... -27783.  86186. 304009.]
Max value: 5772451.0
13.0


In [13]:
newValue_byDate = np.diff(sort_data_byDate[:, cofirmed_cIdx])
print(newValue_byDate.shape)
print(newValue_byDate)

max_value = np.max(newValue_byDate)
print(max_value)

index_max_value = np.argmax(newValue_byDate)
print(index_max_value)

print(sort_data_byDate[index_max_value])
print(sort_data_byDate[index_max_value + 1])

(306428,)
[    13.     -8.     -5. ... -27783.  86186. 304009.]
5772451.0
298067
[298068.      5.     19.   2021.  90687.    929.  46000.]
[ 298069.       5.      19.    2021. 5863138.  107390.  324444.]


### 
- Xác định ngày có số ca hồi phục nhiều nhất. 

In [14]:
index_max_Recover = np.argmax(raw_data[:,recoverds_cIdx])
max_data_Recover = raw_data[index_max_Recover]
print("Ca phục hồi nhiều nhất:\n",max_data_Recover)

Ca phục hồi nhiều nhất:
 [ 179329.      12.      14.    2020.       0.       0. 6399531.]
