### 
- Tách dữ liệu của một quốc gia cụ thể để tập trung phân tích sâu hơn. 
- Tạo một mảng chỉ chứa dữ liệu của một số quốc gia cụ thể. 
- Lọc dữ liệu để chỉ lấy thông tin của một quốc gia xác định.

In [11]:
import numpy as np
filepath = "C:\\fpoly\\Numpy\\Assignment\\"
file_full_name = "Covid-19-Final.csv"
filename_full = filepath + file_full_name

file_name_Country = "Covid-19-Country.csv"
filename_country = filepath + file_name_Country

In [12]:
myDelimiter = ','
maxline = 10
np.set_printoptions(suppress = True, precision = 2, linewidth = 200, formatter={'float': '{:20,.1f}'.format})

In [13]:
country_data = np.genfromtxt(filename_country,
                     delimiter = myDelimiter,
                     dtype = np.str_,
                   skip_header = 1)
#print(country_data)

In [14]:
header_data = np.loadtxt(filename_full,
                     delimiter = myDelimiter,
                     dtype = np.str_,
                     max_rows = 1)
print(header_data)

['SNo' 'ObservationDate' 'Province/State' 'Country/Region' 'Last Update' 'Confirmed' 'Deaths' 'Recovered' 'observation_MM' 'observation_DD' 'observation_YYYY' 'State_ID' 'Country_ID']


In [15]:
indeces_raw = [0,8,9,10,5,6,7,11,12]
raw_data = np.genfromtxt(filename_full,
                        usecols = indeces_raw,
                        delimiter = myDelimiter,
                        skip_header = True)
print(raw_data)
print(raw_data.shape)
SNo_cIdx = 0
MM_cIdx = 1
DD_cIdx = 2
YYYY_cIdx = 3
cofirmed_cIdx = 4
deaths_cIdx = 5
recoverds_cIdx = 6
stateid_cIdex = 7
countryid_cIdex = 8

[[                 1.0                  1.0                 22.0 ...                  0.0                163.0                125.0]
 [                 2.0                  1.0                 22.0 ...                  0.0                198.0                125.0]
 [                 3.0                  1.0                 22.0 ...                  0.0                248.0                125.0]
 ...
 [           306,427.0                  5.0                 29.0 ...              1,324.0                735.0                125.0]
 [           306,428.0                  5.0                 29.0 ...             83,790.0                736.0                215.0]
 [           306,429.0                  5.0                 29.0 ...                  0.0                737.0                146.0]]
(306429, 9)


### 
- Phân tích dịch bệnh Covid-19 của quốc gia Việt Nam

In [16]:
selectedCountryName = "Vietnam"
selectedCountryID = np.where((country_data [:,1] == selectedCountryName))
print(selectedCountryID)
country_id = selectedCountryID[0][0]
print(country_id)

(array([222]),)
222


In [18]:
find_index_Country_data = np.where(raw_data[:,countryid_cIdex] == country_id)
#print(find_Country_data)
country_data = raw_data[find_index_Country_data]
print("Dữ liệu Covid-19 của quốc gia Việt Nam \n",country_data)
print(country_data.shape)
header_data_country = header_data[indeces_raw]
header_data_country_string = ",".join(header_data_country)
print(header_data_country_string)
data_name = filepath + 'Covid-19 VietNam.csv' 
np.savetxt(data_name,country_data,delimiter = myDelimiter,header =header_data_country_string, fmt = "%s")

Dữ liệu Covid-19 của quốc gia Việt Nam 
 [[                82.0                  1.0                 23.0 ...                  0.0                  0.0                222.0]
 [               128.0                  1.0                 24.0 ...                  0.0                  0.0                222.0]
 [               171.0                  1.0                 25.0 ...                  0.0                  0.0                222.0]
 ...
 [           304,302.0                  5.0                 27.0 ...              2,853.0                  0.0                222.0]
 [           305,067.0                  5.0                 28.0 ...              2,896.0                  0.0                222.0]
 [           305,832.0                  5.0                 29.0 ...              2,896.0                  0.0                222.0]]
(493, 9)
SNo,observation_MM,observation_DD,observation_YYYY,Confirmed,Deaths,Recovered,State_ID,Country_ID


### 
- Tính tổng số ca nhiễm, tử vong và hồi phục để hiểu quy mô của dịch bệnh. 


In [19]:
sum_cofirmed = np.sum(raw_data[:,cofirmed_cIdx]) 
print("Tổng số ca nhiễm:",sum_cofirmed)
sum_deaths = np.sum(raw_data[:,deaths_cIdx]) 
print("Tổng số ca tử vong:",sum_deaths)
sum_recoverds = np.sum(raw_data[:,recoverds_cIdx]) 
print("Tổng số ca phục hồi:",sum_recoverds)

Tổng số ca nhiễm: 26252051758.0
Tổng số ca tử vong: 624013017.0
Tổng số ca phục hồi: 15450237912.0


### 
- Tính tổng số ca nhiễm từ một số quốc gia được chọn. 

In [20]:
sum_cofirmed_countryVietNam = np.sum(country_data[:,cofirmed_cIdx])
print("Tổng số ca nhiễm của quốc gia Việt Nam:",sum_cofirmed_countryVietNam)
sum_deaths_countryVietNam = np.sum(country_data[:,deaths_cIdx])
print("Tổng số ca tử vong của quốc gia Việt Nam:",sum_deaths_countryVietNam)
sum_recoverds_countryVietNam = np.sum(country_data[:,recoverds_cIdx])
print("Tổng số ca phục hồi của quốc gia Việt Nam:",sum_recoverds_countryVietNam)

Tổng số ca nhiễm của quốc gia Việt Nam: 615984.0
Tổng số ca tử vong của quốc gia Việt Nam: 10220.0
Tổng số ca phục hồi của quốc gia Việt Nam: 486370.0


### 
- Tính tổng số ca tử vong từ ngày đầu tiên cho đến ngày hiện tại. 
- Mức 1: Thông tin Covid-19 theo từng năm

In [21]:
print(raw_data)
print(raw_data.shape)


[[                 1.0                  1.0                 22.0 ...                  0.0                163.0                125.0]
 [                 2.0                  1.0                 22.0 ...                  0.0                198.0                125.0]
 [                 3.0                  1.0                 22.0 ...                  0.0                248.0                125.0]
 ...
 [           306,427.0                  5.0                 29.0 ...              1,324.0                735.0                125.0]
 [           306,428.0                  5.0                 29.0 ...             83,790.0                736.0                215.0]
 [           306,429.0                  5.0                 29.0 ...                  0.0                737.0                146.0]]
(306429, 9)


In [22]:
unique_yyyy = np.unique(raw_data[:,YYYY_cIdx])
print(unique_yyyy)


[             2,020.0              2,021.0]


In [23]:
groupbyYY_column_names = ['STT','SUm_of_Cofirmed','Sum_of_Deaths','Sum_of_Recovered','YYYY']
NumofRows = len(unique_yyyy)
NumofColumns = len(groupbyYY_column_names)

data_groupby_YYYY = np.full((NumofRows,NumofColumns),0.)
grp_STT_idx = 0
grp_Sum_Confirmed_idx = 1
grp_Sum_Deaths_idx = 2
grp_Sum_Recovered_idx = 3
grp_YYYY_idx = 4

print(groupbyYY_column_names)
print(data_groupby_YYYY)
print(data_groupby_YYYY.shape)

['STT', 'SUm_of_Cofirmed', 'Sum_of_Deaths', 'Sum_of_Recovered', 'YYYY']
[[                 0.0                  0.0                  0.0                  0.0                  0.0]
 [                 0.0                  0.0                  0.0                  0.0                  0.0]]
(2, 5)


In [24]:
for rowI in range(0,NumofRows):
    selectedYYYY = unique_yyyy[rowI]
    
    rIdx_data_byYYYY = np.where(raw_data[:,YYYY_cIdx] == selectedYYYY )
    data_byYYYY = raw_data[rIdx_data_byYYYY[0]]
    print(data_byYYYY.shape)
    
    data_groupby_YYYY[rowI,grp_STT_idx] = rowI + 1
    
    data_groupby_YYYY[rowI,grp_Sum_Confirmed_idx] = data_byYYYY[:,cofirmed_cIdx].sum()
    data_groupby_YYYY[rowI,grp_Sum_Deaths_idx] = data_byYYYY[:,deaths_cIdx].sum()
    data_groupby_YYYY[rowI,grp_Sum_Recovered_idx] = data_byYYYY[:,recoverds_cIdx].sum()
    
    data_groupby_YYYY[rowI,grp_YYYY_idx] = selectedYYYY
    print(data_groupby_YYYY[rowI])
    
header_str = ",".join(groupbyYY_column_names)
np.savetxt(filepath+'Total_Covid-19_by_Year.csv',data_groupby_YYYY,delimiter = myDelimiter,header = header_str,fmt = "%d,%d,%d,%d,%d")   

(192466, 9)
[                 1.0      7,640,152,768.0        223,445,222.0      4,746,191,037.0              2,020.0]
(113963, 9)
[                 2.0     18,611,898,990.0        400,567,795.0     10,704,046,875.0              2,021.0]


### 
- Mức 2: Thông tin Covid-19 của các tháng theo năm

In [25]:
unique_yyyy_mm = np.unique(raw_data[:, [YYYY_cIdx, MM_cIdx]], axis=0)
sorted_indices = np.lexsort((unique_yyyy_mm[:, 1], unique_yyyy_mm[:, 0]))
unique_yyyy_mm_sorted = unique_yyyy_mm[sorted_indices]
print(unique_yyyy_mm_sorted)


[[             2,020.0                  1.0]
 [             2,020.0                  2.0]
 [             2,020.0                  3.0]
 [             2,020.0                  4.0]
 [             2,020.0                  5.0]
 [             2,020.0                  6.0]
 [             2,020.0                  7.0]
 [             2,020.0                  8.0]
 [             2,020.0                  9.0]
 [             2,020.0                 10.0]
 [             2,020.0                 11.0]
 [             2,020.0                 12.0]
 [             2,021.0                  1.0]
 [             2,021.0                  2.0]
 [             2,021.0                  3.0]
 [             2,021.0                  4.0]
 [             2,021.0                  5.0]]


In [26]:
groupbyYYMM_column_names = ['STT','SUm_of_Cofirmed','Sum_of_Deaths','Sum_of_Recovered','YYYY','MM']
NumofRows_yyyy_mm = len(unique_yyyy_mm_sorted)
NumofColumns_yyyy_mm = len(groupbyYYMM_column_names) 
data_groupby_YYYYMM = np.full((NumofRows_yyyy_mm, NumofColumns_yyyy_mm), 0.)
grp_MM_idx = 5
print(groupbyYYMM_column_names)
print(data_groupby_YYYYMM)
print(data_groupby_YYYYMM.shape)

['STT', 'SUm_of_Cofirmed', 'Sum_of_Deaths', 'Sum_of_Recovered', 'YYYY', 'MM']
[[                 0.0                  0.0                  0.0                  0.0                  0.0                  0.0]
 [                 0.0                  0.0                  0.0                  0.0                  0.0                  0.0]
 [                 0.0                  0.0                  0.0                  0.0                  0.0                  0.0]
 [                 0.0                  0.0                  0.0                  0.0                  0.0                  0.0]
 [                 0.0                  0.0                  0.0                  0.0                  0.0                  0.0]
 [                 0.0                  0.0                  0.0                  0.0                  0.0                  0.0]
 [                 0.0                  0.0                  0.0                  0.0                  0.0                  0.0]
 [                 

In [27]:
for rowI in range(0,NumofRows_yyyy_mm):
    selectedYYYY,selectedMM = unique_yyyy_mm_sorted[rowI]
    rIdx_data_byYYYYMM = np.where((raw_data[:, YYYY_cIdx] == selectedYYYY) &
                                  (raw_data[:, MM_cIdx] == selectedMM))
    data_byYYYYMM = raw_data[rIdx_data_byYYYYMM[0]]
    print(data_byYYYYMM.shape)
    
    data_groupby_YYYYMM[rowI, grp_STT_idx] = rowI + 1
    
    data_groupby_YYYYMM[rowI, grp_Sum_Confirmed_idx] = data_byYYYYMM[:, cofirmed_cIdx].sum()
    data_groupby_YYYYMM[rowI, grp_Sum_Deaths_idx] = data_byYYYYMM[:, deaths_cIdx].sum()
    data_groupby_YYYYMM[rowI, grp_Sum_Recovered_idx] = data_byYYYYMM[:, recoverds_cIdx].sum()
    data_groupby_YYYYMM[rowI, grp_YYYY_idx] = selectedYYYY
    data_groupby_YYYYMM[rowI, grp_MM_idx] = selectedMM
    print(data_groupby_YYYYMM[rowI])

(513, 9)
[                 1.0             38,980.0                905.0                897.0              2,020.0                  1.0]
(2383, 9)
[                 2.0          1,671,960.0             46,898.0            380,837.0              2,020.0                  2.0]
(7943, 9)
[                 3.0          8,896,092.0            386,607.0          2,707,333.0              2,020.0                  3.0]
(9700, 9)
[                 4.0         63,155,257.0          4,200,500.0         16,422,184.0              2,020.0                  4.0]
(12420, 9)
[                 5.0        144,857,836.0          9,605,979.0         54,218,282.0              2,020.0                  5.0]
(21500, 9)
[                 6.0        246,800,814.0         13,294,590.0        118,665,388.0              2,020.0                  6.0]
(22921, 9)
[                 7.0        431,962,227.0         18,393,019.0        242,303,677.0              2,020.0                  7.0]
(23136, 9)
[                 8.0

In [28]:
header_str_2 = ",".join(groupbyYYMM_column_names)
np.savetxt(filepath+'Total_Covid-19_by_YearMonth.csv',data_groupby_YYYYMM,delimiter = myDelimiter,header = header_str_2,fmt = "%d,%d,%d,%d,%d,%d"
)   

### 
- Mức 3: Thông tin Covid-19 ngày theo tháng theo năm

In [29]:
unique_yyyy_mm_dd = np.unique(raw_data[:, [YYYY_cIdx, MM_cIdx,DD_cIdx]], axis=0)
sorted_indices = np.lexsort((unique_yyyy_mm_dd[:, 2], unique_yyyy_mm_dd[:, 1],unique_yyyy_mm_dd[:,0]))
unique_yyyy_mm_dd_sorted = unique_yyyy_mm_dd[sorted_indices]
print(unique_yyyy_mm_dd_sorted)


[[             2,020.0                  1.0                 22.0]
 [             2,020.0                  1.0                 23.0]
 [             2,020.0                  1.0                 24.0]
 ...
 [             2,021.0                  5.0                 27.0]
 [             2,021.0                  5.0                 28.0]
 [             2,021.0                  5.0                 29.0]]


In [30]:
groupbyYYMMDD_column_names = ['STT','SUm_of_Cofirmed','Sum_of_Deaths','Sum_of_Recovered','YYYY','MM','DD']
NumofRows_yyyy_mm_dd = len(unique_yyyy_mm_dd_sorted)
NumofColumns_yyyy_mm_dd = len(groupbyYYMMDD_column_names)  # Giữ nguyên cấu trúc cột
data_groupby_YYYYMMDD = np.full((NumofRows_yyyy_mm_dd, NumofColumns_yyyy_mm_dd), 0.)
grp_DD_idx = 6


In [31]:
for rowI in range(0,NumofRows_yyyy_mm_dd):
    selectedYYYY,selectedMM,selectedDD = unique_yyyy_mm_dd_sorted[rowI]
    rIdx_data_byYYYYMMDD = np.where((raw_data[:, YYYY_cIdx] == selectedYYYY) &
                                  (raw_data[:, MM_cIdx] == selectedMM) &
                                   (raw_data[:,DD_cIdx] == selectedDD ))
    data_byYYYYMMDD = raw_data[rIdx_data_byYYYYMMDD[0]]
    #print(rIdx_data_byYYYYMMDD.shape)
    
    data_groupby_YYYYMMDD[rowI, grp_STT_idx] = rowI + 1
    
    data_groupby_YYYYMMDD[rowI, grp_Sum_Confirmed_idx] = data_byYYYYMMDD[:, cofirmed_cIdx].sum()
    data_groupby_YYYYMMDD[rowI, grp_Sum_Deaths_idx] = data_byYYYYMMDD[:, deaths_cIdx].sum()
    data_groupby_YYYYMMDD[rowI, grp_Sum_Recovered_idx] = data_byYYYYMMDD[:, recoverds_cIdx].sum()
    data_groupby_YYYYMMDD[rowI, grp_YYYY_idx] = selectedYYYY
    data_groupby_YYYYMMDD[rowI, grp_MM_idx] = selectedMM
    data_groupby_YYYYMMDD[rowI, grp_DD_idx] = selectedDD
    print(data_groupby_YYYYMMDD[rowI])

[                 1.0                557.0                 17.0                 30.0              2,020.0                  1.0                 22.0]
[                 2.0              1,097.0                 34.0                 60.0              2,020.0                  1.0                 23.0]
[                 3.0                941.0                 26.0                 39.0              2,020.0                  1.0                 24.0]
[                 4.0              1,437.0                 42.0                 42.0              2,020.0                  1.0                 25.0]
[                 5.0              2,118.0                 56.0                 56.0              2,020.0                  1.0                 26.0]
[                 6.0              2,927.0                 82.0                 65.0              2,020.0                  1.0                 27.0]
[                 7.0              5,578.0                131.0                108.0              2,020.0 

[               350.0         86,546,014.0          1,875,953.0         48,488,548.0              2,021.0                  1.0                  5.0]
[               351.0         87,329,386.0          1,891,006.0         48,801,673.0              2,021.0                  1.0                  6.0]
[               352.0         88,210,223.0          1,905,926.0         49,125,604.0              2,021.0                  1.0                  7.0]
[               353.0         89,013,445.0          1,921,092.0         49,422,867.0              2,021.0                  1.0                  8.0]
[               354.0         89,774,439.0          1,933,877.0         49,753,112.0              2,021.0                  1.0                  9.0]
[               355.0         90,363,573.0          1,942,225.0         50,023,662.0              2,021.0                  1.0                 10.0]
[               356.0         90,983,503.0          1,952,549.0         50,313,950.0              2,021.0 

[               418.0        119,877,179.0          2,654,577.0         67,895,903.0              2,021.0                  3.0                 14.0]
[               419.0        120,226,080.0          2,661,398.0         68,185,782.0              2,021.0                  3.0                 15.0]
[               420.0        120,699,093.0          2,671,288.0         68,452,267.0              2,021.0                  3.0                 16.0]
[               421.0        121,238,378.0          2,681,413.0         68,716,803.0              2,021.0                  3.0                 17.0]
[               422.0        121,792,101.0          2,691,987.0         68,985,879.0              2,021.0                  3.0                 18.0]
[               423.0        122,353,780.0          2,702,386.0         69,264,940.0              2,021.0                  3.0                 19.0]
[               424.0        122,852,600.0          2,710,432.0         69,523,151.0              2,021.0 

In [32]:
header_str_3 = ",".join(groupbyYYMMDD_column_names)
np.savetxt(filepath+'Total_Covid-19_by_YearMonthDay.csv',data_groupby_YYYYMMDD,delimiter = myDelimiter,header = header_str_3,fmt = "%d,%d,%d,%d,%d,%d,%d"
)   

####
- Tính trung bình Covid-19 theo từng ngày

In [33]:
groupbyYYMMDD_column_names = ['STT','Mean_of_Cofirmed','Mean_of_Deaths','Mean_of_Recovered','YYYY','MM','DD']
NumofRows_yyyy_mm_dd = len(unique_yyyy_mm_dd_sorted)
NumofColumns_yyyy_mm_dd = len(groupbyYYMMDD_column_names)  # Giữ nguyên cấu trúc cột
data_mean_groupby_YYYYMMDD = np.full((NumofRows_yyyy_mm_dd, NumofColumns_yyyy_mm_dd), 0.)
grp_Mean_Confirmed_idx = 1
grp_Mean_Deaths_idx = 2
grp_Mean_Recovered_idx = 3


In [35]:
for rowI in range(0,NumofRows_yyyy_mm_dd):
    selectedYYYY,selectedMM,selectedDD = unique_yyyy_mm_dd_sorted[rowI]
    rIdx_data_byYYYYMMDD = np.where((raw_data[:, YYYY_cIdx] == selectedYYYY) &
                                  (raw_data[:, MM_cIdx] == selectedMM) &
                                   (raw_data[:,DD_cIdx] == selectedDD ))
    data_byYYYYMMDD = raw_data[rIdx_data_byYYYYMMDD[0]]
    #print(rIdx_data_byYYYYMMDD.shape)
    
    data_mean_groupby_YYYYMMDD[rowI, grp_STT_idx] = rowI + 1
    
    data_mean_groupby_YYYYMMDD[rowI, grp_Mean_Confirmed_idx] = data_byYYYYMMDD[:, cofirmed_cIdx].mean()
    data_mean_groupby_YYYYMMDD[rowI, grp_Mean_Deaths_idx] = data_byYYYYMMDD[:, deaths_cIdx].mean()
    data_mean_groupby_YYYYMMDD[rowI, grp_Mean_Recovered_idx] = data_byYYYYMMDD[:, recoverds_cIdx].mean()
    data_mean_groupby_YYYYMMDD[rowI, grp_YYYY_idx] = selectedYYYY
    data_mean_groupby_YYYYMMDD[rowI, grp_MM_idx] = selectedMM
    data_mean_groupby_YYYYMMDD[rowI, grp_DD_idx] = selectedDD
    print(data_mean_groupby_YYYYMMDD[rowI])

[                 1.0                 13.9                  0.4                  0.8              2,020.0                  1.0                 22.0]
[                 2.0                 22.9                  0.7                  1.2              2,020.0                  1.0                 23.0]
[                 3.0                 21.9                  0.6                  0.9              2,020.0                  1.0                 24.0]
[                 4.0                 31.2                  0.9                  0.9              2,020.0                  1.0                 25.0]
[                 5.0                 43.2                  1.1                  1.1              2,020.0                  1.0                 26.0]
[                 6.0                 55.2                  1.5                  1.2              2,020.0                  1.0                 27.0]
[                 7.0                103.3                  2.4                  2.0              2,020.0 

[               417.0            156,231.1              3,462.8             88,431.7              2,021.0                  3.0                 13.0]
[               418.0            156,702.2              3,470.0             88,752.8              2,021.0                  3.0                 14.0]
[               419.0            157,158.3              3,479.0             89,131.7              2,021.0                  3.0                 15.0]
[               420.0            157,776.6              3,491.9             89,480.1              2,021.0                  3.0                 16.0]
[               421.0            158,481.5              3,505.1             89,825.9              2,021.0                  3.0                 17.0]
[               422.0            159,205.4              3,518.9             90,177.6              2,021.0                  3.0                 18.0]
[               423.0            159,939.6              3,532.5             90,542.4              2,021.0 

[               494.0            222,158.9              4,619.1            140,053.2              2,021.0                  5.0                 29.0]


###
- Lấy thông tin dịch bệnh Covid-19 của Đông Nam Á

In [39]:
country_data = np.genfromtxt(filename_country,
                     delimiter = myDelimiter,
                     dtype = np.str_,
                   skip_header = 1)
print(country_data)

[['0' '"(\'St. Martin\'-)"']
 ['1' '"Bahamas- The"']
 ['2' '"Gambia- The"']
 ['3' 'Afghanistan']
 ['4' 'Albania']
 ['5' 'Algeria']
 ['6' 'Andorra']
 ['7' 'Angola']
 ['8' 'Antigua and Barbuda']
 ['9' 'Argentina']
 ['10' 'Armenia']
 ['11' 'Aruba']
 ['12' 'Australia']
 ['13' 'Austria']
 ['14' 'Azerbaijan']
 ['15' 'Bahamas']
 ['16' 'Bahrain']
 ['17' 'Bangladesh']
 ['18' 'Barbados']
 ['19' 'Belarus']
 ['20' 'Belgium']
 ['21' 'Belize']
 ['22' 'Benin']
 ['23' 'Bhutan']
 ['24' 'Bolivia']
 ['25' 'Bosnia and Herzegovina']
 ['26' 'Botswana']
 ['27' 'Brazil']
 ['28' 'Brunei']
 ['29' 'Bulgaria']
 ['30' 'Burkina Faso']
 ['31' 'Burma']
 ['32' 'Burundi']
 ['33' 'Cabo Verde']
 ['34' 'Cambodia']
 ['35' 'Cameroon']
 ['36' 'Canada']
 ['37' 'Cape Verde']
 ['38' 'Cayman Islands']
 ['39' 'Central African Republic']
 ['40' 'Chad']
 ['41' 'Channel Islands']
 ['42' 'Chile']
 ['43' 'China']
 ['44' 'Colombia']
 ['45' 'Comoros']
 ['46' 'Congo (Brazzaville)']
 ['47' 'Congo (Kinshasa)']
 ['48' 'Costa Rica']
 ['49' '

In [40]:
#print(country_data)
selectedCountryNames = ["Vietnam", "Thailand", "Indonesia","Malaysia","Philippines","Laos","Cambodia","Brunei","Singapore"]
selectedCountryIDs = np.where(np.isin(country_data[:, 1],  selectedCountryNames))
country_ids = country_data[selectedCountryIDs, 0].astype(int).flatten()
print(country_ids)

[ 28  34  96 113 127 162 185 204 222]


In [41]:
for rowI in range(0, NumofRows_yyyy_mm_dd):
    selectedYYYY, selectedMM, selectedDD = unique_yyyy_mm_dd_sorted[rowI]
    rIdx_data_byYYYYMMDD = np.where(
        (raw_data[:, YYYY_cIdx] == selectedYYYY) &
        (raw_data[:, MM_cIdx] == selectedMM) &
        (raw_data[:, DD_cIdx] == selectedDD) &
        np.isin(raw_data[:, countryid_cIdex], country_ids) )
    
    data_byYYYYMMDD = raw_data[rIdx_data_byYYYYMMDD[0]]
    
    data_groupby_YYYYMMDD[rowI, grp_STT_idx] = rowI + 1
    data_groupby_YYYYMMDD[rowI, grp_Sum_Confirmed_idx] = data_byYYYYMMDD[:, cofirmed_cIdx].sum()
    data_groupby_YYYYMMDD[rowI, grp_Sum_Deaths_idx] = data_byYYYYMMDD[:, deaths_cIdx].sum()
    data_groupby_YYYYMMDD[rowI, grp_Sum_Recovered_idx] = data_byYYYYMMDD[:, recoverds_cIdx].sum()
    data_groupby_YYYYMMDD[rowI, grp_YYYY_idx] = selectedYYYY
    data_groupby_YYYYMMDD[rowI, grp_MM_idx] = selectedMM
    data_groupby_YYYYMMDD[rowI, grp_DD_idx] = selectedDD
    
    #print(f"Date: {selectedYYYY}-{selectedMM}-{selectedDD}")
    print(data_groupby_YYYYMMDD[rowI])


[                 1.0                  4.0                  0.0                  2.0              2,020.0                  1.0                 22.0]
[                 2.0                  7.0                  0.0                  2.0              2,020.0                  1.0                 23.0]
[                 3.0                 10.0                  0.0                  3.0              2,020.0                  1.0                 24.0]
[                 4.0                 14.0                  0.0                  3.0              2,020.0                  1.0                 25.0]
[                 5.0                 18.0                  0.0                  6.0              2,020.0                  1.0                 26.0]
[                 6.0                 20.0                  0.0                  6.0              2,020.0                  1.0                 27.0]
[                 7.0                 28.0                  0.0                  6.0              2,020.0 

Date: 2021.0-1.0-18.0
[               363.0          1,655,407.0             36,933.0          1,404,489.0              2,021.0                  1.0                 18.0]
Date: 2021.0-1.0-19.0
[               364.0          1,670,848.0             37,325.0          1,416,004.0              2,021.0                  1.0                 19.0]
Date: 2021.0-1.0-20.0
[               365.0          1,689,470.0             37,667.0          1,429,138.0              2,021.0                  1.0                 20.0]
Date: 2021.0-1.0-21.0
[               366.0          1,706,164.0             38,099.0          1,441,620.0              2,021.0                  1.0                 21.0]
Date: 2021.0-1.0-22.0
[               367.0          1,725,924.0             38,387.0          1,452,804.0              2,021.0                  1.0                 22.0]
Date: 2021.0-1.0-23.0
[               368.0          1,744,392.0             38,660.0          1,467,453.0              2,021.0                  

Date: 2021.0-3.0-18.0
[               422.0          2,505,349.0             53,410.0          2,236,686.0              2,021.0                  3.0                 18.0]
Date: 2021.0-3.0-19.0
[               423.0          2,520,402.0             53,624.0          2,245,139.0              2,021.0                  3.0                 19.0]
Date: 2021.0-3.0-20.0
[               424.0          2,535,858.0             53,766.0          2,253,133.0              2,021.0                  3.0                 20.0]
Date: 2021.0-3.0-21.0
[               425.0          2,549,597.0             53,912.0          2,275,867.0              2,021.0                  3.0                 21.0]
Date: 2021.0-3.0-22.0
[               426.0          2,564,578.0             54,084.0          2,284,780.0              2,021.0                  3.0                 22.0]
Date: 2021.0-3.0-23.0
[               427.0          2,577,632.0             54,266.0          2,293,672.0              2,021.0                  

Date: 2021.0-5.0-23.0
[               488.0          3,690,963.0             72,559.0          3,304,979.0              2,021.0                  5.0                 23.0]
Date: 2021.0-5.0-24.0
[               489.0          3,711,729.0             72,813.0          3,321,058.0              2,021.0                  5.0                 24.0]
Date: 2021.0-5.0-25.0
[               490.0          3,732,451.0             73,111.0          3,334,011.0              2,021.0                  5.0                 25.0]
Date: 2021.0-5.0-26.0
[               491.0          3,753,572.0             73,517.0          3,350,026.0              2,021.0                  5.0                 26.0]
Date: 2021.0-5.0-27.0
[               492.0          3,780,503.0             73,974.0          3,363,459.0              2,021.0                  5.0                 27.0]
Date: 2021.0-5.0-28.0
[               493.0          3,807,817.0             74,453.0          3,377,099.0              2,021.0                  

###
- Thông tin Covid-19 của 10 ngày đầu tiên 

In [43]:
unique_yyyy_mm_dd = np.unique(raw_data[:, [YYYY_cIdx, MM_cIdx,DD_cIdx]], axis=0)
sorted_indices = np.lexsort((unique_yyyy_mm_dd[:, 2], unique_yyyy_mm_dd[:, 1],unique_yyyy_mm_dd[:,0]))
unique_yyyy_mm_dd_sorted = unique_yyyy_mm_dd[sorted_indices]
top_day = 10
day_Top_first = unique_yyyy_mm_dd_sorted[:top_day]
print(day_Top_first)


[[             2,020.0                  1.0                 22.0]
 [             2,020.0                  1.0                 23.0]
 [             2,020.0                  1.0                 24.0]
 [             2,020.0                  1.0                 25.0]
 [             2,020.0                  1.0                 26.0]
 [             2,020.0                  1.0                 27.0]
 [             2,020.0                  1.0                 28.0]
 [             2,020.0                  1.0                 29.0]
 [             2,020.0                  1.0                 30.0]
 [             2,020.0                  1.0                 31.0]]


In [44]:
arr_top_year = np.unique(day_Top_first[:,0],axis = 0)
arr_top_month = np.unique(day_Top_first[:,1],axis = 0)
print(arr_top_month)
arr_top_day = np.unique(day_Top_first[:,2],axis = 0)
print(arr_top_day)

[                 1.0]
[                22.0                 23.0                 24.0                 25.0                 26.0                 27.0                 28.0                 29.0                 30.0
                 31.0]


In [45]:
index_topN = np.where(
    (np.isin(raw_data[:, YYYY_cIdx], arr_top_year)) &  
    (np.isin(raw_data[:, MM_cIdx], arr_top_month)) &  
    (np.isin(raw_data[:, DD_cIdx], arr_top_day))      
)

data_topN_day = raw_data[index_topN]

print(data_topN_day)
print(data_topN_day.shape)


[[                 1.0                  1.0                 22.0 ...                  0.0                163.0                125.0]
 [                 2.0                  1.0                 22.0 ...                  0.0                198.0                125.0]
 [                 3.0                  1.0                 22.0 ...                  0.0                248.0                125.0]
 ...
 [               511.0                  1.0                 31.0 ...                  0.0                  0.0                198.0]
 [               512.0                  1.0                 31.0 ...                  0.0                681.0                 43.0]
 [               513.0                  1.0                 31.0 ...                  0.0                  0.0                109.0]]
(513, 9)
